
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=".git*"
        path: ./
        remote_path: ${{ secrets.SERVER_PATH }}
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_port: ${{ secrets.SERVER_PORT }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_KEY }}

